#TODO: this is kinda gross, fix strings and stuff
gpus: "0,"
base_config: 'configs/single_image.yaml'
# TODO: WARNING TO USER, DO NOT USE TILDE!!!
model_ckpt_path: "models/ldm/text2img-large/model.ckpt"
init_img_path: "init_images"
outputs_path: "OUTPUTS" # stores output images for each iteration of each embedding
filtered_path: "FILTERED" # stores filtered images for training each new iteration of each embedding
init_word: "\"*\"" # TODO: STRING FORMATTING 
iterations: 2

# training image generation params
ddim_eta: 0.0
n_samples: 2
n_iter: 1
scale: 7.0
ddim_steps: 20
num_prompts: 2
num_attire: 1

# prompt generation
simple_attire: true
# image filtering 
filter_ratio: 0.5

# embedding names
embedding_names:
  [
    # "w",
    # "b",
    "example"
  ]